### ISSUE TITLE
Agree on data format

### ISSUE THREAD

**Issue by mrtnrey** [inbo/crow#11]
Data format should be agreed upon.

I propose to use the .vp extension for an individual profile (one radar, one timestamp) as they come out of the vol2bird algorithm (on stdout).
.vp files are then concatenated to .vpts files _per day_ and _per radar_.
For the current day, .vpts files will then be updated in real time in the open data repository.

On the open data repository, vp-files of the recent day will be found, and an archive of vpts files. As such, an **initial call** of the visualisation suite would first grab the **.vpts** files, and can then **poll** for **newly available .vp files** to update the visualisation accordingly.

In attachment, data for two days with intense migration for bewid.
Headers are omitted in .vpts files (except the first one).

Please let me know if this is a suitable fileformat&procedure.

[bewid.zip](https://github.com/inbo/crow/files/3309869/bewid.zip)

**Comment by peterdesmet** [comment]
@mrtnrey sorry for late reaction, some thoughts:

## Filename

1. simple line concatenation from `vp` to `vpts` is easy and straightforward 👌 In a sense, a `vp` file is a short `vpts` file then and the only difference is length of time?
1. rather than `vp` and `vpts` extension, I would use `.txt`: it will load in more programs
1. what is the `.vbrd` element in the filename, can it be omitted?
1. What is the `00` in the datetime of the filename, can it be omitted?

```
20190330*00*.bewid.vbrd.vpts
20190330*00*001600.bewid.vbrd.vp
```

## Format

1. if I understand correctly, the file content (including headers) is structured **exactly** like it comes out of stdout? That's a good argument to keep it that way, but I (and other users) will have to find a way to deal with the fixed-width (rather than delimited) column format
1. keeping the first header for `vpts` files is fine, but the `# polar volume input: /tmp/2019033100001600dBZ.pvol.h5` is a slightly misleading

## Procedure

1. if I understand correctly, the vpts file for today will be updated in real time every time a vp file comes in (awesome!) 👌 
1. if the vpts file is updated, then I think the visualization only needs to load `vpts` files (and never `vp` files)

**Comment by niconoe** [comment]
Closing since the current viz works fine with the file as they are, will reopen if more specific questions or issue arise.
