### ISSUE TITLE
Calculate total number of birds for radar and time period

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#112]
This will be calculated on the fly for the current selection.

**Comment by peterdesmet** [comment]
@mrtnrey how do we calculate this number?

**Comment by mrtnrey** [comment]
It is a bit difficult (impossible?) to put a very concrete number on the total number of birds in the figure. The main reason is that you don't know how many times the same bird is scanned by the radar in subsequent radar scans. So my first attempt uses a kind of mean number for the whole period shown.

From the VID (birds per square km)→ calculate the mean VID over graph shown = call it _N_
The area scanned by the vol2bird procedure is a donut shape (5km→35km in range from the radar) covering - at ground - a surface of <img src="https://render.githubusercontent.com/render/math?math=\pi*(17.5^2-2.5^2) \rm{km}^2=942.5\rm{km}^2">
Hence, the calculation of _N_ is intrinsically based on the detection of (roughly) _Ntot=N*942.5_ on average for that period.

The text on top of the figure:
> **During the time interval shown below, the _Helchteren_ radar detected a mean value of _N_ birds per square kilometer<sup>1</sup>. The total number of birds seen by the radar was about _Ntot_ on average for this period.**
> <sub><sup>1</sup>Local movements close the the ground are not detected by the radar.</sub>

The _Helchteren_ tag is then obviously replaced by the current radar.

**Comment by peterdesmet** [comment]
Ping @CeciliaNilsson709: do you has experience in calculating total number of birds?

**Comment by mrtnrey** [comment]
**Second attempt** by using the MTR.

From the MTR data → calculate the mean MTR over the graph shown, call it _N_. This is the mean number of birds travelling through a transect of 1km, per hour.  Multiply by 24h to get the total number of birds for the 1 day period (or multiply by 72 when showing 3 days) travelling through a screen of 1km. To obtain an absolute number, multiply by the transect as covered by the vol2bird procedure  (5km→35km in range) hence 30km.

The text on top of the figure:
> **During the time interval shown below, the _Helchteren_ radar saw roughly Nx24 birds pass by<sup>1</sup> through an hypothetical screen of 1km wide. The total number of birds seen by the radar passing by was about Nx24x30 for this time period.**

I think this number might be more understandable, but less certain too.

@peterdesmet @robinbrabant please comment on both propositions. Tnx!

**Comment by CeciliaNilsson709** [comment]
I don't have a ton of experience calculating absolute numbers, but in general we have stuck to the MTR's over density since density is not always easy to wrap your head around, considering sampling frequencies and birds moving more or less fast through the volume between scans, just as mentioned above.

Furthermore, in the density version, isn't it a problem to not include the sampling frequency when calculating Ntot? If you only use the mean density over time, N, times the surface, you will get the mean number of birds passed over total area but not the total numbers of birds passed, which would require calculating a mean N over the total surface per time unit and then adding them up, right?

MTR is more reliable since it gives a snapshot estimate of how many birds are passing right then, so taking the mean of MTR times the number of hours should give an accurate estimate of how many birds have passed (1km transect) during that period, as described. When calculating the absolute number however, I am wondering if you shouldn't use the transect length through the total volume rather than the range, so 30+30 rather then 30? Not sure 🤔.

So, I my vote would be on using MTR. What you guys are doing seems really cool, can't wait to see the finished result!

**Comment by peterdesmet** [comment]
Thanks @CeciliaNilsson709 and @mrtnrey! I'd opt for the MTR approach, seems the safest bet. Maybe we should also just express it as MTR (= over 1km) rather than expending it to the whole area of the radar, which doesn't give the user that much more information anyway.

> Nx24 birds were passing over a transect of 1 km ...

**Comment by mrtnrey** [comment]
Thanks Cecilia for your comprehensive comments!

First of all: you're right about 30+30 in the MTR version. Should be 60 indeed. So N<sub>mean</sub>x24x60.

Then, for the density version, what I wanted to express is a "typical" density for that day. So a typical snapshot of that day would contain x birds. I admit this is less interesting from an ecology point of view. But personally I find this a bit more reliable since it doesn't rely on the speed estimate.

All in all, both absolute numbers (densiy and MTR) will be very rough estimates anyway. If you and Peter consider the MTR-approach as the less uncertain, we can go for that one. Maybe rounding to the closest multiple of 100 would be something to consider (to reflect the inherent uncertainty).

**Comment by robinbrabant** [comment]
I agree with the MTR option, and with Peter's suggestion to just keep it at a 1 km front (instead of the 60km of the entire Vol2Bird volume). I think this is the clearest and most comprehensible for the users.

**Comment by peterdesmet** [comment]
I think we can phrase it the most succinctly near the VPI chart, as such:

> This chart shows the **total number of birds** in the sky (all heights) at any giving moment. In total, it shows **2.600 birds** flying over a 1 km transect.

<img width="916" alt="Screenshot 2021-02-10 at 18 26 34" src="https://user-images.githubusercontent.com/600993/107547257-8a701100-6bcd-11eb-8860-f2e66a75a987.png">

The previous version was:

> This chart shows the same information, but sums bird densities over height, thus giving a rough idea of the **total number of birds** in the sky at any given moment.

**Comment by robinbrabant** [comment]
Sounds good to me.

**Comment by peterdesmet** [comment]
@niconoe I have updated the descriptions, but `x` should be replaced by:

    24h: average MTR for that 24h * 24, rounded to nearest 100
    72h: average MTR for that 72h * 72, rounded to nearest 100

**Comment by niconoe** [comment]
That's now implemented. Don't hesitate to have a look at the [actual implementation](https://github.com/inbo/crow/blob/23593ccef261e3ae28698dab4ffd5789ff49a7f5/src/components/Home.vue#L421-L435), because I have some difficulty to wrap my head around it, so I may have misunderstood the explanations above.

(what confuses me is that I consider the MTR values I have as instantaneous samples - every 10 minutes. I can easily process an average of those values, but I don't understand how to add the "time" component and go from this "instantenous average" to some meaningful value over a given period of time - so far I just multiply by 24 or 72 as suggested by @peterdesmet just above).

**Comment by peterdesmet** [comment]
Hi Nico, MTR is a rate, so it is not time dependent (it is always "per hour"). It is like measuring a water flow rate every 10 minutes. You can easily take the average to know the average rate (getting rid of fluctuations). And to have an idea of how much water passed you can multiply the rate by time.

**Comment by niconoe** [comment]
haha got it, thanks a lot! So I think we have a correct implementation, then!

**Comment by peterdesmet** [comment]
Yes, I just added some numbers up manually by looking at the chart and I'm getting about the same.
