### ISSUE TITLE
UTC or local times?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#14]
Should the charts show UTC or local times. Currently set to local, by having `type: time` rather than `type: utc` in vega: https://vega.github.io/vega/docs/scales/#time

**Comment by peterdesmet** [comment]
As mentioned by @mrtnrey times should be local time, so fireworks effect are displayed at midnight: https://github.com/inbo/crow/issues/25#issuecomment-574655181

I would add the option (for researchers) to display in UTC time as well.

**Comment by niconoe** [comment]
Okay, I'll update the code so it makes a clear distinction between:

- The timestamp in the data files (always in UTC)
- The local time at the radar and date (depending on its timezone, also take into account daylight saving time)
- The local timezone of the visitor's browser

In practice, that will allow:

- To add new radars everywhere in the world
- Show their data either in the (radar) local time (the default), or in UTC (if requested)

Thankfully the [Moment timezone](https://momentjs.com/timezone/) library will take care of all the details.

**Comment by niconoe** [comment]
There's now a basic implementation for the VP Chart. Note to self: next steps are:

- [ ] Extend to VPI Chart and Timeline chart (should we move the conversions to the parent component? Less flexible, but less code duplication and better performance - conversion is only done once)
- [ ] Form: allow choosing between UTC and local (by default) time display.
- [ ] Maybe: Make clear (under the graph near the axis?) how the time is shown.
- [ ] Maybe: show the timezone of the selected radar, alongside its country. Should we rething the radar metadata display to have something nicer and more complete?

**Comment by peterdesmet** [comment]
I would not mention timezone of radar in radar metadata

**Comment by niconoe** [comment]
@peterdesmet : it is needed, because the radar data comes in UTC, and we want to be able to display it in local time, so we need to do conversions at some point.

What we could do if it bothers you is to infer it from the country, but that'll add code complexity and stop working if we ever add radar in countries that cover multiple time zones.

**Comment by peterdesmet** [comment]
Ok, I was just wondering if we should display it. But we could, as:

> Helchteren (UTC+1) is located in Belgium.

**Comment by niconoe** [comment]
Indeed! But it's UTC+1 during winter and UTC+2 during summer, and that may change in the future 🤔😱

**Comment by peterdesmet** [comment]
Well, up to you if you want to implement daylight savings time 😂

**Comment by niconoe** [comment]
Well, it's already implemented (not by me, in [moment-timezone](https://momentjs.com/timezone/)), and CROW knows when to switch between the two. So it's just a matter of how to display it in the form!

**Comment by peterdesmet** [comment]
How to display, as:

> Helchteren (UTC+1) is located in Belgium.

With e.g. UTC+2 in summer.

**Comment by niconoe** [comment]
Well, when if you use the app close to the daylight saving time enter/exit dates, you might very well show a period that includes UTC+1 and UTC+2 😱. That's why I had initially shown the timezone string (that encompass those details).

But the current option (no radar time shown in form) is fine too. If we want to show detailed radar metadata, we can still implement on a different page or section (see #44)
