### ISSUE TITLE
Show day/night periods on graph?

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#15]
Is that *important*, *nice to have* or *necessary*?

If we go for it: should we use the radar latitude/longitude (we currently don't have this data) or do we use approximate values since all the radars are relatively close (at the planet's scale).

**Comment by peterdesmet** [comment]
I would consider that `important`: most of the migration peaks happen around sunset, so it is very important information to have.

I would not use approximate lat/long, because we want the charts to work for any radar. Also, we'll have to calculate sunrise/sunset for each day. Let me check how bioRad is doing this.

**Comment by niconoe** [comment]
Note to self: [SunCalc](https://github.com/mourner/suncalc) seems 👌 .

**Comment by niconoe** [comment]
Some basic implementation is done, open specific issues for change and improvements.
