### ISSUE TITLE
VPTS chart: show day/night/twilight

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#41]
Even though this is not implemented in bioRad, it would be nice if day/night/twilight could be shown as areas on the VPTS chart as well. The colour (gray) should be visually different from the colours used for density and the density data take priority (i.e. a layer higher).

**Comment by mrtnrey** [comment]
Point of attention: how do you show a time interval with missing data? You have to take care that the shading for day/night/twilight is not interfering with the shading you might use to indicate _missing data_.
Nevertheless, I think showing day/night/twilight is very important indeed, since it's a main driver for bird activity.

**Comment by niconoe** [comment]
Indeed, for the moment I don't see how we could add more gray blocks on this chart without interfering with the heat map (density) itself, hence the current system with a different bar representing this data over the chart. (those gray blocks would also have to work with the BIRDTAM color scheme, if we try to implement it).

Another possibility would be to have on the chart a (more or less) horizontal ligne representing the height of the sun (with respect to the horizon). Since it would be a line it would clash less with the heat map data. (but I'm not sure it's overall a better solution than the current one).

Any opinion?

**Comment by peterdesmet** [comment]
Missing data is indeed shown as a gray area in bioRad, but not yet in our charts and I don't think we should represent it that way. Currently it shows as white, because the current density gradient starts at gray. I would not opt for the height of the sun as a line.

I think it can work fairly well if:

- Density blocks have a transparency of e.g. 20%: on days the white will bleed through, on nights the gray
- Nights are displayed as the discussed gray areas (with twilight zone)
- Missing data are represented another way (e.g. red lines for start - end)

**Comment by peterdesmet** [comment]
@niconoe I thought of an alternative way to display twilight information on both charts, that I think could work well:

![twilight](https://user-images.githubusercontent.com/600993/75241207-fe02ed80-57c5-11ea-9f0d-008443570aa1.png)

- It doesn't draw attention away from the chart
- It doesn't interfere with the data
- It's closely positioned to the time information
- It uses the same visual representation on both charts

**Comment by niconoe** [comment]
I think it would work really well, will make a test soon!

**Comment by peterdesmet** [comment]
Colours are:

```
#AFBBC0: day
#486FA3: twilight
#162C54: night
```

**Comment by niconoe** [comment]
@peterdesmet : can you have a look (at https://inbo.github.io/crow/)?

If it looks good, I think we can finally close #41, #31 and #39. We'll create new issues if further adjustments are required.

**Comment by peterdesmet** [comment]
It looks really good, the issues can be closed!
