### ISSUE TITLE
Den Helder (NLDHL) not available, Dutch radar is Herwijnen (NLHRW)

### ISSUE THREAD

**Issue by mrtnrey** [inbo/crow#42]
~~Den Helder~~ → Herwijnen
Dutch radar: KMI does not receive data from Den Helder, but Herwijnen (NLHRW)
For metadata on the radar, visit (BEHEL not yet included)
https://www.eumetnet.eu/wp-content/themes/aeron-child/observations-programme/current-activities/opera/database/OPERA_Database/index.html

**Comment by niconoe** [comment]
I just replaced it!

While we're at radar metadata, I have a couple more questions:

- I guess the metadata on the website above is accurate (so I can use it to have correct coordinates for the various radars - the one we use are currently approximate)?
- Since BEHEL is not there, do you have its coordinates (I currently use: latitude: 51.0743268, longitude: 5.3844822)?
- I see the server (https://crow.weernet.be/) has data files for a few more radars, should we also show them?
- Is this list of radar to show subject to frequent changes?

Thanks!

**Comment by mrtnrey** [comment]
- Yes, I confirm the coordinates on the eumetnet.eu map are very accurate. Note the "ODIM code" in the metadata: this is the one we are using
- Coordinate of BEHEL is a few hunderds of meters off. The correct one is 51.069199, 5.406138. You can see the radar on Google maps here https://goo.gl/maps/xJgCEA9np23mBxB27
- Yes, you can show all radars EXCEPT the French ones (FRAVE and FRABB). We need an agreement for that one, once CROW is in production.
- No frequent changes expected.

**Comment by peterdesmet** [comment]
Nice, that also removes a "TODO" from our codebase. Closing this issue.
