### ISSUE TITLE
Allow to navigate through time

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#55]
Allow the user to jump the date(time) forwards and backwards in the selected interval steps (24h, 96h).

- Implement by having buttons before and after date input field (I can style those)
- Should update value of date field, which then triggers a reload
- ~~Implementing this for the 1h interval might be difficult, because a) no indication of the hour is given and b) the message `Charts will be centered on noon for selected date.` would be wrong. I would wager removing the 1h interval option altogether.~~: see #51

**Comment by niconoe** [comment]
Basic +1/-1 day navigation implemented. Next steps:

- Improve styling
- Decide if we want to jump in 4 days increment when "96 hours" is selected. It might indeed makes sense to buttons to navigate to the next period (instead of the next day), but in that case I wonder if the buttons location (just next to date) is right, or if the button effect might confuse the user. 1 hour period won't work properly, but it doesn't really matter since it will be disabled in production.
- Something easy to implement and that would give us more flexibility (for the period durations and the navigate logic): remove `Charts will be centered on noon for selected date` and just replace the date field by a datetime field. It would be preconfigured at noon, but can be updated (by the user manually, or by the increment/decrement period) if needed.

**Comment by peterdesmet** [comment]
See my suggestion in https://github.com/inbo/crow/pull/60.

On point 3: I would not allow the user to update time: it's too small scale to have that configured by the user.
