### ISSUE TITLE
Add other calculated properties to integrateProfile

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#6]
In addition to `mtr`, also return `rtr`, `vid`, `vir` in `integrateProfile()` data.

**Comment by niconoe** [comment]
... and later also show them, obviously.

**Comment by niconoe** [comment]
See: Stijn's pull request + his suggestion to properly test this by comparing output to Biorad's.

**Comment by niconoe** [comment]
Update January: @peterdesmet just confirmed the need for this, with the following precisions:

- This will appear on the same graph than MTR (only two graphs on the page)
- Only one value is show at the time, the user can choose (radio buttons directly on the chart top-right?)

**Comment by peterdesmet** [comment]
@niconoe that is correct: the exact position of the buttons is to be decided, but near the chart is preferred.

**Comment by niconoe** [comment]
Thanks for the precision! Reopening, since this is not yet implemented.

**Comment by niconoe** [comment]
Update: basic implementation done, but seems to hava data errors. To be checked.

**Comment by niconoe** [comment]
Update: fixed a bunch of issues thanks to TypeScript, data should be manually checked, but at least the graph doesn't show a flat line anymore :)

**Comment by niconoe** [comment]
Update: now implemented unit test for that (output compared to bioRad, used as a reference).

We can see that currently, `MTR` and `VID` values are correct , while `RTR`and `VIR` are not.

**Comment by niconoe** [comment]
UPDATE: 

- the discrepancy in RTR disappear if we set the VVP threshold to 0 (default value=2). I did so because I didn't notice this filtering in bioRad's integration function. I guess bioRad does it at another time, it would be interesting to know why (=> to investigate, just to be sure we're doing the right thing).

- the discrepancy in VIR is not explained yet, but the difference seems not huge (33 vs 34 for example). This is unaffected bu the VVP threshold.
