### ISSUE TITLE
Incorrect BirdTAM colors?

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#76]
<img width="507" alt="Screenshot 2020-09-25 at 14 32 44" src="https://user-images.githubusercontent.com/386387/94267545-142f8280-ff3c-11ea-8d9d-65608b92e20d.png">

... Looks like white should be 0, not 9 (and everything shifted).

The issue seems limited to the legend (not the actual chart values)

**Comment by peterdesmet** [comment]
From https://www.flysafe-birdtam.eu/profiles.html:

<img width="79" alt="Screenshot 2020-10-21 at 10 20 11" src="https://user-images.githubusercontent.com/600993/96693010-088e7a80-1387-11eb-8159-48cd5ddac24a.png">

**Comment by peterdesmet** [comment]
FYI https://github.com/inbo/crow/issues/16#issuecomment-624065275:

> Note to self: reimplement using a (D3) quantize scale?

**Comment by niconoe** [comment]
Renamed value "9", now "> 8" (consistent with flysafe).

Another probable issue: we actually never have 0 (white) values, even when the bird density is 0. That's different from Flysafe, reviewing right now.

**Comment by niconoe** [comment]
Update: just fixed the legend color ordering bug.

**Comment by niconoe** [comment]
Hey @mrtnrey:

As explained above, I'm trying to assess the correctness of the BirdTAM mode in Crow. I compared the display to the FlySafe website, but it's somewhat difficult.

For example, on CROW, we never have 0 (white) values, while that happens a lot on FlySafe. But due to my (probably wrong) understanding of the explanations of Hans van Gasteren (see #16), the absence of values seems quite logical (at te end of the process, we "floor" a value that's always above 1).

I'm therefore wondering if someone (you? Hans?) could either:

- provide a list of related input (density) and output (BirdTAM score) values that I can test my formula around.
- review my short JS implementation: `score = Math.floor(1.4427 * Math.log(density + 1) + 1.6781);`. Since I wasn't sure if 1.4427 was a value to multiply to or the logarithm base, I also tried `score = Math.floor(logBase(density + 1, 1.4427) + 1.6781);`, but the resulting chart looks weirder.

Thanks 🙏

**Comment by peterdesmet** [comment]
Pinging @hvangasteren. Hans, do you have a translation for bird density to BirdTAM score?

**Comment by mrtnrey** [comment]
Maybe a naive question : is the JS code correctly processing the "nan" values in the vpts file?

**Comment by niconoe** [comment]
No, that's a good question. I have to check what else happens to those values between the data load and the code above.

**Comment by niconoe** [comment]
@mrtnrey: when the data file is loaded, I consider that a NaN value in `dens` as 0 (this is later passed to the code above). Is that correct? 

The absence of 0 values is therefore because the `Math.floor(1.4427 * Math.log(0 + 1) + 1.6781)` expression gives 1.

And sorry for my terrible math skills, I think this discussion will make that obvious :)

**Comment by hvangasteren** [comment]
Hoi Peter,This is already in your crow tool?Our do you mean a reference? See the paper in EcographyHansVerzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Peter Desmet <notifications@github.com> Datum: 23-10-20  12:37  (GMT+01:00) Aan: inbo/crow <crow@noreply.github.com> Cc: Hans van Gasteren <hvangasteren@xs4all.nl>, Mention <mention@noreply.github.com> Onderwerp: Re: [inbo/crow] Incorrect BirdTAM colors? (#76) 
Pinging @hvangasteren. Hans, do you have a translation for bird density to BirdTAM score?

**Comment by peterdesmet** [comment]
Thanks Hans, would you have a link to the paper? This is already implemented in our CROW tool (see e.g. https://inbo.github.io/crow/#/?radar=behel&date=2020-10-20&interval=24&timedisplay=radarLocal&vpColorScheme=birdtam&vpiMode=mtr) but we want to verify we are assigning the colours correctly.

**Comment by hvangasteren** [comment]
All,

 

From my script it says:

density = data(:,8:end)';  -> array with bird densities from vol2bird

densitybirdtam = 1.4427.*log(density+1)+1.6781; -> conversion of bird density to birdtam values

densitybirdam = floor(densitybirdtam) -> only integer values

densitybirdtam( density==0 ) = 0; -> when density values are zero, birdtam values should be zero too, probably something due to rounding (or NaN)

 

Link to the paper: https://onlinelibrary.wiley.com/doi/10.1111/ecog.04125

 

Hope this helps, 

Hans

**Comment by mrtnrey** [comment]
> The absence of 0 values is therefore because the Math.floor(1.4427 * Math.log(0 + 1) + 1.6781) expression gives 1.

Is this the cause of the greenish background then? So in JS you could check like this:

`(density == 0 ? 0 : Math.floor(1.4427 * Math.log(density + 1) + 1.6781) );`

**Comment by hvangasteren** [comment]
Peter,

 

Can you add the other Dutch radar too, Den Helder? I’m using your CROW tool quite often, since it’s updated more often each hour.

 

I know value 9 doesn’t exist, but extreme values do exist pretty often. Otherwise you call them “>8”?

 

Thanks for this work

**Comment by hvangasteren** [comment]
2 points:

 

1.       LOG in my formula means LN (sorry for the addition of 1)

2.       Minimum value is indeed 1 (very low), therefore I additionally set NaN values to 0 with the my last row below

 

Sorry for the lack of taking care of extremely low values J

Hans

 

 

 

 

 

From: Hans van Gasteren <hvangasteren@xs4all.nl> 
Sent: vrijdag 23 oktober 2020 13:31
To: 'inbo/crow' <reply@reply.github.com>; 'inbo/crow' <crow@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [inbo/crow] Incorrect BirdTAM colors? (#76)

 

All,

 

From my script it says:

density = data(:,8:end)';  -> array with bird densities from vol2bird

densitybirdtam = 1.4427.*log(density+1)+1.6781; -> conversion of bird density to birdtam values

densitybirdam = floor(densitybirdtam) -> only integer values

densitybirdtam( density==0 ) = 0; -> when density values are zero, birdtam values should be zero too, probably something due to rounding (or NaN)

 

Link to the paper: https://onlinelibrary.wiley.com/doi/10.1111/ecog.04125

 

Hope this helps, 

Hans

**Comment by niconoe** [comment]
Thanks a lot @hvangasteren and @mrtnrey!

I (hopefully) fixed the algorithm according to the last explanations, can you check on https://inbo.github.io/crow/#/?

To me the visual output seems better, but still a bit different (for the same time/radar) than what I see on https://www.flysafe-birdtam.eu/profiles.html. Do you have any idea of why?

**Comment by mrtnrey** [comment]
The initial filtering of the radar files is a bit different, e.g. Flysafe is using static ground clutter maps, and we don't.
This can lead to some differences, especially in the lowest layers.

I would not be too worried about such small differences. Bird density quantification is inherently quite uncertain: it gives you a gross estimate, not an exact number, and the end-user should be aware of this.
