### ISSUE TITLE
Data repository: final location is ftp://opendata.meteo.be/observations/radar/vbird

### ISSUE THREAD

**Issue by mrtnrey** [inbo/crow#78]
The data repository on RMI is now put into production. Please let the CROW app https://inbo.github.io/crow/ point to

ftp://opendata.meteo.be/observations/radar/vbird/

The files in the temporary data repository (that was set up for development purposes) on "crow.weernet.be" were copied to this location. The repo on crow.weernet.be will be deprecated soon.

**Comment by peterdesmet** [comment]
Thanks @mrtnrey, that's good news. We'll take this into account!

**Comment by mrtnrey** [comment]
Thanks @niconoe . Concerning your two points:

- I will ask our IT to look at the possibility of serving over https. I agree ftp as protocol might not be the most convenient choice from the viewpoint of client side apps.
- Yes, you can use all 9 radars for the project!

**Comment by niconoe** [comment]
Brilliant, thanks a lot!

**Comment by niconoe** [comment]
@mrtnrey : while I can manually browse the files on the new server, the CROW app is not able to load them.

It appears it's because the Apache server doesn't return the `access-control-allow-origin` header (as the temporary repo did). Can you ask your system administrator to have a look ? I'd like this header to have the '*' value, just like the example configuration shown at https://enable-cors.org/server_apache.html.

Thanks a lot!

**Comment by mrtnrey** [comment]
I asked our IT to adapt the .htaccess file on https://opendata.meteo.be/ftp/
I'll keep you updated.

**Comment by mrtnrey** [comment]
@niconoe should be OK now. Can you test it? Tnx.

**Comment by niconoe** [comment]
Seems to work perfectly, I'll update the website soon to include all 9 radars and load data from the new server.

**Comment by niconoe** [comment]
Now updated at https://inbo.github.io/crow/
